### ISSUE TITLE
Handle Null Main Camera in Render Method

### ISSUE THREAD

**Issue by leAdmin666** [Influence-Engine/Influence#3]
**Currently, the engine crashes if there is no main camera when the Render method is called. To improve the robustness of the engine and ensure it does not crash in such scenarios, we need to implement better error handling. This would not only prevent crashes but also enhance the overall stability of the engine.**

![image](https://github.com/Influence-Engine/Influence/assets/50849877/73871602-ab7c-41cc-852f-89314cafddd4)

### Steps to Reproduce:
1. **Create a GameObject and add the component that contains the Render method.**
2. **Ensure there is no main camera set in the scene.**

### Expected Behavior:
**The engine should not crash. Instead, it should gracefully handle the absence of a main camera, possibly logging an error message or using a default fallback behavior.**

### Actual Behavior:
**The engine crashes due to a null reference when trying to access Camera.mainCamera.**

**Comment by realQuartzi** [comment]
Good catch!

For this case the ideal way to handle it would be all together to not allow the rendering to occur. 
Since if there is no camera then we should not render objects that are in world space.

Additionally on top of that the camera itself is currently in a provoking state as it is not setting itself as mainCamera on creation, regardless of the constructor having it set.

Will look into this further soon!

**Comment by realQuartzi** [comment]
Fixed in d2eb492cdca6db44a262e543552bb8031ace0765. <3
